server:
  port: 9000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/my_first_postgreSQL
    username: postgres
    password: 171103
  jpa:
    properties:
      hibernate:
        show_sql: false
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
